import { describe, expect, it, vi } from "vitest";

vi.mock("server-only", () => ({}));

import { getShopeeAuthorizationOrigin } from "@/lib/shopee/config";

describe("Shopee authorization origins", () => {
  it("uses the sandbox hostname generated by the Shopee Open Platform Console", () => {
    expect(getShopeeAuthorizationOrigin("sandbox")).toBe(
      "https://open.sandbox.test-stable.shopee.com",
    );
  });

  it("keeps production authorization on the production host", () => {
    expect(getShopeeAuthorizationOrigin("production")).toBe("https://open.shopee.com");
  });
});
